"""Command-line entrypoint: run one customer through the full pipeline.

    python -m agent.cli --customer-id 7590-VHVEG

Prints a readable retention report. Uses the real saved model, the real SHAP
explainer, and the LLM when one is configured; otherwise the deterministic
engine produces the recommendation and the report says so.
"""

from __future__ import annotations

import argparse
import json

from agent.models.evidence import CustomerEvidence
from agent.models.recommendation import PROVIDER_DETERMINISTIC, RetentionRecommendation
from agent.providers.llm_provider import build_provider
from agent.services.evidence_builder import (
    build_customer_evidence,
    build_evidence_for_dataset_customer,
)
from agent.services.recommendation_service import RecommendationService
from agent.strategies.evaluator import evaluate_customer

SEPARATOR = "=" * 78
REPORT_DRIVER_COUNT = 5


# =========================================================
# 1. RENDER THE REPORT
# =========================================================


def render_report(evidence: CustomerEvidence, recommendation: RetentionRecommendation) -> str:
    """Format the end-to-end result for a human reader."""
    evaluation = evaluate_customer(evidence)
    lines: list[str] = []

    def section(title: str) -> None:
        lines.append("")
        lines.append(title)
        lines.append("-" * len(title))

    lines.append(SEPARATOR)
    lines.append("RETENTION INTELLIGENCE REPORT")
    lines.append(SEPARATOR)

    section("CUSTOMER")
    lines.append(f"  Customer ID     : {evidence.customer_id}")
    lines.append(f"  Model version   : {evidence.model_version}")

    section("CHURN PROBABILITY / RISK LEVEL")
    lines.append(f"  Churn probability : {evidence.churn_probability:.4f}")
    lines.append(f"  Risk level        : {evidence.risk_level}")
    lines.append(f"  Predicted class   : {evidence.prediction}")

    section(f"TOP SHAP DRIVERS (top {REPORT_DRIVER_COUNT} of {len(evidence.top_drivers)} evaluated)")
    for index, driver in enumerate(evidence.top_drivers[:REPORT_DRIVER_COUNT], start=1):
        lines.append(
            f"  {index}. {driver.feature:<18} value={str(driver.value):<16} "
            f"shap={driver.shap_value:+.4f}  impact={driver.impact:.2%}  {driver.direction}"
        )

    section("CANDIDATE STRATEGIES (ranked by evidence alignment)")
    for index, candidate in enumerate(evaluation.candidates, start=1):
        lines.append(
            f"  {index}. {candidate.strategy_id:<30} score={candidate.alignment_score:.4f}"
        )
        lines.append(f"     {candidate.rationale}")
    if evaluation.rejected:
        lines.append("  Not eligible:")
        for strategy_id, reason in evaluation.rejected:
            lines.append(f"     - {strategy_id}: {reason}")

    section("SELECTED STRATEGY")
    lines.append(
        f"  {recommendation.selected_strategy.strategy_id} "
        f"({recommendation.selected_strategy.strategy_name})"
    )

    section("AI RECOMMENDATION")
    lines.append(f"  {recommendation.recommendation}")
    generated_by = (
        "deterministic strategy engine (no LLM)"
        if recommendation.provider == PROVIDER_DETERMINISTIC
        else f"LLM provider '{recommendation.provider}'"
    )
    lines.append(f"  [generated by: {generated_by}]")
    if recommendation.fallback_reason:
        lines.append(f"  [fallback reason: {recommendation.fallback_reason}]")

    section("REASONING")
    for bullet in recommendation.reasoning:
        lines.append(f"  - {bullet}")

    section("SUPPORTING EVIDENCE")
    for item in recommendation.supporting_evidence:
        lines.append(
            f"  - {item.feature} = {item.value} (shap {item.shap_value:+.4f}, {item.direction})"
        )

    section("OBJECTIVE")
    lines.append(f"  {recommendation.objective}")

    section("CONFIDENCE")
    lines.append(f"  {recommendation.confidence}")
    lines.append(f"  {recommendation.confidence_rationale}")

    section("LIMITATIONS")
    for limitation in recommendation.limitations:
        lines.append(f"  - {limitation}")

    section("HUMAN APPROVAL REQUIRED")
    lines.append(f"  {recommendation.requires_human_approval}")

    lines.append("")
    lines.append(SEPARATOR)
    return "\n".join(lines)


# =========================================================
# 2. CLI
# =========================================================


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a retention recommendation for one customer."
    )
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--customer-id", default=None, help="customerID from the raw dataset.")
    source.add_argument("--json", dest="payload", default=None, help="Customer record as JSON.")
    parser.add_argument(
        "--no-llm",
        action="store_true",
        help="Force the deterministic engine even when an LLM is configured.",
    )
    parser.add_argument("--json-output", action="store_true", help="Print JSON instead of a report.")
    return parser.parse_args()


def main() -> None:
    args = _parse_args()

    if args.customer_id:
        evidence = build_evidence_for_dataset_customer(args.customer_id)
    else:
        evidence = build_customer_evidence(json.loads(args.payload))

    provider = None if args.no_llm else build_provider()
    recommendation = RecommendationService(provider=provider).recommend(evidence)

    if args.json_output:
        print(recommendation.model_dump_json(indent=2))
    else:
        print(render_report(evidence, recommendation))


if __name__ == "__main__":
    main()
