"""Output contracts for the what-if simulator and strategy comparison engine.

Every number in these models is computed by the system from the saved model and
the real SHAP explainer. The AI layer contributes prose only — it can neither
write nor overwrite a probability, a SHAP value, or a ranking score.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator

from agent.models.evidence import Direction, RiskLevel
from agent.models.recommendation import PROVIDER_DETERMINISTIC
from agent.models.scenario import UnsimulatableIntervention, WHATIF_DISCLAIMER

# Limitations attached to every what-if result. They describe the method, so the
# system owns them rather than the LLM.
WHATIF_LIMITATIONS: tuple[str, ...] = (
    WHATIF_DISCLAIMER,
    "The simulation evaluates the trained model's sensitivity to hypothetical feature "
    "values; it does not estimate the effect of an intervention.",
    "SHAP values explain model behaviour and do not establish causality.",
    "Actual customer behaviour may differ from model estimates.",
    "Scenario profiles are hypothetical and require human validation before any action.",
)


# =========================================================
# 1. SHAP SNAPSHOTS AND DELTAS
# =========================================================


class DriverSnapshot(BaseModel):
    """One SHAP driver at a point in time (baseline or scenario)."""

    model_config = ConfigDict(frozen=True)

    feature: str
    value: Any = None
    shap_value: float
    direction: Direction
    impact: float = Field(..., ge=0.0, le=1.0)


class DriverDelta(BaseModel):
    """How one feature's SHAP contribution moved between baseline and scenario.

    This is the part that answers "*why* did the model's estimate change?" rather
    than just "did it change?".
    """

    model_config = ConfigDict(frozen=True)

    feature: str
    baseline_shap: float
    scenario_shap: float
    shap_change: float
    changed_by_scenario: bool = Field(
        ..., description="True when the scenario directly altered this feature's value."
    )


# =========================================================
# 2. BASELINE
# =========================================================


class BaselinePrediction(BaseModel):
    """The customer's current, unmodified prediction and explanation."""

    model_config = ConfigDict(frozen=True)

    churn_probability: float = Field(..., ge=0.0, le=1.0)
    risk_level: RiskLevel
    prediction: int = Field(..., ge=0, le=1)
    model_version: str
    top_drivers: list[DriverSnapshot] = Field(default_factory=list)


# =========================================================
# 3. SCENARIO OUTCOMES
# =========================================================


class RankingFactors(BaseModel):
    """The transparent inputs to a scenario's ranking score.

    Exposed on every outcome so a reviewer can reproduce the score by hand
    instead of trusting an opaque number.
    """

    model_config = ConfigDict(frozen=True)

    model_response: float = Field(..., ge=0.0, le=1.0)
    evidence_alignment: float = Field(..., ge=0.0, le=1.0)
    driver_targeting: float = Field(..., ge=0.0, le=1.0)
    conflict_penalty_applied: bool = False


class ScenarioOutcome(BaseModel):
    """Result of evaluating one hypothetical profile against the trained model."""

    model_config = ConfigDict(frozen=True)

    # --- Identity ---
    scenario_id: str
    scenario_name: str
    strategy_id: str
    description: str
    rationale: str
    changed_features: dict[str, Any]
    simulatable: Literal[True] = True

    # --- Model response ---
    baseline_probability: float = Field(..., ge=0.0, le=1.0)
    scenario_probability: float = Field(..., ge=0.0, le=1.0)
    absolute_probability_change: float
    relative_probability_change: float
    percentage_point_change: float

    # --- Risk bands (existing thresholds, never redefined here) ---
    baseline_risk_level: RiskLevel
    scenario_risk_level: RiskLevel
    risk_level_changed: bool

    # --- Explanation comparison ---
    baseline_top_drivers: list[DriverSnapshot] = Field(default_factory=list)
    scenario_top_drivers: list[DriverSnapshot] = Field(default_factory=list)
    driver_deltas: list[DriverDelta] = Field(default_factory=list)

    # --- Ranking ---
    ranking_score: float = Field(..., ge=0.0, le=1.0)
    ranking_factors: RankingFactors
    conflicts_with_evidence: bool = False
    conflict_reason: str | None = None

    # --- Careful, non-causal wording generated by the system ---
    model_based_interpretation: str
    limitations: list[str] = Field(default_factory=lambda: list(WHATIF_LIMITATIONS))

    @property
    def model_estimate_improved(self) -> bool:
        """True when the model's estimate is lower under the hypothetical profile."""
        return self.absolute_probability_change < 0


class ScenarioRejection(BaseModel):
    """A scenario that was not evaluated, and why.

    One bad scenario must never abort a comparison, so rejections are reported
    alongside the successful outcomes.
    """

    model_config = ConfigDict(frozen=True)

    scenario_id: str
    scenario_name: str = ""
    reason: str
    simulatable: bool = True  # False when the model simply cannot represent it


# =========================================================
# 4. FULL COMPARISON RESULT
# =========================================================


class WhatIfResult(BaseModel):
    """Baseline, every evaluated scenario, the ranking, and the AI reading of it."""

    model_config = ConfigDict(extra="forbid")

    customer_id: str | None = None
    customer_profile: dict[str, Any] = Field(default_factory=dict)
    baseline: BaselinePrediction
    candidate_strategy_ids: list[str] = Field(default_factory=list)

    scenarios: list[ScenarioOutcome] = Field(default_factory=list)
    rejected_scenarios: list[ScenarioRejection] = Field(default_factory=list)
    unsimulatable_interventions: list[UnsimulatableIntervention] = Field(default_factory=list)

    # --- System-owned selection ---
    recommended_scenario_id: str | None = None
    selection_reason: str = ""
    ranking_methodology: str = ""

    # --- AI-owned prose ---
    ai_interpretation: str | None = None
    ai_considerations: list[str] = Field(default_factory=list)
    ai_alternative_scenario_id: str | None = Field(
        default=None,
        description="Set when the AI reads a different scenario as most promising than the ranking did.",
    )
    provider: str = PROVIDER_DETERMINISTIC
    fallback_reason: str | None = None

    # --- Governance ---
    limitations: list[str] = Field(default_factory=lambda: list(WHATIF_LIMITATIONS))
    requires_human_approval: bool = True
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    @field_validator("requires_human_approval")
    @classmethod
    def _approval_is_mandatory(cls, value: bool) -> bool:
        """A simulation is decision support; it can never authorise an action."""
        if value is not True:
            raise ValueError("requires_human_approval must always be True.")
        return True

    @property
    def recommended_scenario(self) -> ScenarioOutcome | None:
        for outcome in self.scenarios:
            if outcome.scenario_id == self.recommended_scenario_id:
                return outcome
        return None

    @property
    def generated_by_llm(self) -> bool:
        return self.provider != PROVIDER_DETERMINISTIC
